### ISSUE TITLE
black screen after update (no change in config.js)

### ISSUE THREAD

**Issue by Dres49** [andrecarlucci/MMM-DailyDilbert#3]
Hi Andrecarlucci,

thanks for writing this module and your support.

Around beginning of october I did a MM-softwareupdate and immediately (without changing the config.js)
the screen went black. I found that disabeling the dilbert-modules solves the problem no other modules shows this problem.

But I like the funny comics ;-)

The forum showed this thread with a software bug at the same time:
https://forum.magicmirror.builders/topic/13774/2-13-back-screen-translation-file-error-fix 
I applied the recommended changes/updates but still if I activate the Dilbert module the screen stays black.
The config-check does not show an error message - i.e. no syntax error (additionally it worked before the update).
I updated the MM software and Dilbert module as well - but no change still black screen with activated Dilbert module. 

Do you have any ideas how to solve the problem?

Thanks and best regards,

Dres49.

**Comment by chrisparker787** [comment]
Same here - any working fix?

**Comment by Dres49** [comment]
No - so far no solution or answer to this problem :(

**Comment by Dres49** [comment]
Dear all,

I did not found the root cause for the problem but I found a solution:
1) remove the module:
cd ~/MagicMirror
rm -rf modules/MMM-DailyDilbert
2) reboot the raspi: 
sudo reboot
3) install the module again
--> this worked for my installation.

Thanks to morozgrafix for his explanation - how to remove a module.

Best regards.
Dres49.
