### ISSUE TITLE
Broken as of October 2021

### ISSUE THREAD

**Issue by kwinz** [andrecarlucci/MMM-DailyDilbert#4]
Just like DailyXKCD, this module also does not work any more.
If it is referenced in `config.js` the MagicMirror app is just blank black at startup and doesn't work any more.

**Comment by andrecarlucci** [comment]
It's been too long. I will find some time to fix this. Tks.

**Comment by andrecarlucci** [comment]
@kwinz, it's fixed, could you retry and confirm, please?

**Comment by kwinz** [comment]
Thanks for the fix @andrecarlucci . I can confirm it's working now.
